version: 2.1

executors:
  arm64:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

jobs:
  build:
    executor: arm64
    steps:
      - checkout
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: pwd

      - run:
          name: Install Basic Dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y \
              curl \
              git \
              unzip \
              xz-utils \
              zip

      - run:
          name: Install Mesa Dependencies
          command: |
            sudo apt-get install -y \
              libglu1-mesa

      - run:
          name: Install Build Dependencies
          command: |
            sudo apt-get install -y \
              clang cmake git \
              ninja-build pkg-config \
              libgtk-3-dev liblzma-dev \
              libstdc++-12-dev

      - run:
          name: Install Flutter SDK
          command: |
            curl -LO https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_3.24.0-stable.tar.xz
            tar -xf flutter_linux_3.24.0-stable.tar.xz
            echo 'export PATH="$HOME/project/flutter/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV
            flutter --version

      - run:
          name: Configure Flutter for Linux
          command: |
            flutter config --enable-linux-desktop

      - run:
          name: Build Flutter app for Linux ARM64
          command: |
            flutter build linux --release --target-platform=linux-arm64

      - store_artifacts:
          path: build/linux/arm64/release/bundle
          destination: build-output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
