version: 2.1

executors:
  arm64:
    machine:
      image: ubuntu-2204:2023.07.1
    resource_class: arm.medium

jobs:
  build:
    executor: arm64
    steps:
      - checkout
      - run: uname -a
      - run: echo "Hello, Arm!"
      - run: pwd

      - run:
          name: Install Basic Dependencies
          command: |
            sudo apt-get update -y
            sudo apt-get install -y \
              curl \
              git \
              unzip \
              xz-utils \
              zip

      - run:
          name: Install Mesa Dependencies
          command: |
            sudo apt-get install -y \
              libglu1-mesa

      - run:
          name: Install Build Dependencies
          command: |
            sudo apt-get install -y \
              clang cmake git \
              ninja-build pkg-config \
              libgtk-3-dev liblzma-dev \
              libstdc++-12-dev

      - run:
          name: Install Flutter SDK for ARM64
          command: |
            FLUTTER_VERSION="3.24.0"
            wget -O flutter.tar.xz "https://storage.googleapis.com/flutter_infra_release/releases/stable/linux/flutter_linux_${FLUTTER_VERSION}-stable.tar.xz"
            tar xf flutter.tar.xz
            echo 'export PATH="$HOME/project/flutter/bin:$PATH"' >> $BASH_ENV
            source $BASH_ENV

            # Download Dart SDK for ARM64
            DART_VERSION="3.5.0"
            wget -O dart-sdk.zip "https://storage.googleapis.com/dart-archive/channels/stable/release/${DART_VERSION}/sdk/dartsdk-linux-arm64-release.zip"
            unzip dart-sdk.zip -d flutter/bin/cache/
            mv flutter/bin/cache/dart-sdk flutter/bin/cache/dart-sdk-arm64

            # Use ARM64 Dart SDK
            echo 'export DART_SDK="$HOME/project/flutter/bin/cache/dart-sdk-arm64"' >> $BASH_ENV
            source $BASH_ENV

            flutter --version

      - run:
          name: Configure Flutter for Linux
          command: |
            flutter config --enable-linux-desktop

      - run:
          name: Build Flutter app for Linux ARM64
          command: |
            flutter build linux --release --target-platform=linux-arm64

      - store_artifacts:
          path: build/linux/arm64/release/bundle
          destination: build-output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
