version: 2.1

executors:
  arm64:
    machine:
      image: ubuntu-20.04-arm64

#TEST Trigger
jobs:
  build:
    executor: arm64
    steps:
      - checkout

      - run:
          name: Install Dependencies
          command: |
            sudo apt-get update
            sudo apt-get install -y \
              cmake \
              ninja-build \
              libgtk-3-dev \
              liblzma-dev \
              libssl-dev \
              pkg-config \
              zlib1g-dev

      - run:
          name: Install Flutter
          command: |
            git clone https://github.com/flutter/flutter.git -b stable --depth 1
            export PATH="$PATH:`pwd`/flutter/bin"
            flutter doctor

      - run:
          name: Build Flutter app for Linux ARM64
          command: |
            flutter config --enable-linux-desktop
            flutter build linux --release --target-platform=linux-arm64

      - store_artifacts:
          path: build/linux/arm64/release/bundle
          destination: build-output

workflows:
  version: 2
  build-and-test:
    jobs:
      - build
